### PR TITLE
added CreatorBuilder (pretty dirty)

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
Requires the latest changes from Creator 0.4.0-dev (template additions, fixes)

### CODE REVIEW

**Comment by winksaville** [comment]
Thanks, I'll take a look soon.

**Comment by NiklasRosenstein** [comment]
Hi Wink!

> With gcc on linux I to have move the '$!<' before $!Libs so main.o is before the libraries:

Oh right, that's quite possibly necessary. I sometimes forget about that. I was testing on Mac with Clang, and it works there.

> Then if I execute 'ninja -v -j14' I see the failure that libL001.a, libL003.a and libL004.a haven't been created yet. And very oddly step [21/22] is the link step for testapp while step[22/22] is creating archive for libL003.a, this definitely feels wrong.

You're right, there must be something wrong. It should only link after all libraries have been built, since the testapp depends on all libraries. Unfortunately, I can't reproduce this on Mac. I will check it on Linux soon.

> Another thing, what I'm looking for is not so much how long it takes for cmake, meson or creator to run the first time, but more importantly how long it takes to just do the build steps there after.

I understand. But I think that highly depends on the back-end, for which it is Ninja in all three cases (except you can also choose other output formats for CMake). For Creator, you can use the `-e` option to force an export only and not invoke Ninja under the hood.

> In your case you're hiding ninja behind creator so your code is part of the build step, but that's not the case with cmake or meson.

I don't necessarily _hide_ it, it's always there and you can use Ninja directly to run the build as well after Creator has generated it. But I found it to be more convenient to use the Creator command-line interface over Ninja. I understand that for projects of this size, that is hardly an option due to the long startup time.

---

**Update** I can't reproduce it on Linux either. It builds everything in order. What Ninja version are you using? The Ninja version on my Linux machine is rather old (1.3.4).

On another side note, I'm wondering why GCC complains about the undefined references? Does GCC not accept absolute paths to static libraries? I used `nm` to check if the `libLXXX.a` files really contain the functions, and they do.

```
niklas@vbox-ubuntu:~/Desktop/gen_srcs$ ninja -j 14
[22/22] gcc -std=c99 /home/niklas/Desktop/gen_srcs/test/buil...in.o -o /home/niklas/Desktop/gen_srcs/test/build/bin/testapp
FAILED: gcc -std=c99 /home/niklas/Desktop/gen_srcs/test/build/libs/libL000.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL001.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL002.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL003.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL004.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL005.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL006.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL007.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL008.a /home/niklas/Desktop/gen_srcs/test/build/libs/libL009.a /home/niklas/Desktop/gen_srcs/test/build/obj/testapp/main.o -o /home/niklas/Desktop/gen_srcs/test/build/bin/testapp
/home/niklas/Desktop/gen_srcs/test/build/obj/testapp/main.o: In function `main':
main.c:(.text+0x5): undefined reference to `func1'
main.c:(.text+0xa): undefined reference to `func2'
main.c:(.text+0xf): undefined reference to `func3'
main.c:(.text+0x14): undefined reference to `func4'
main.c:(.text+0x19): undefined reference to `func5'
main.c:(.text+0x1e): undefined reference to `func6'
main.c:(.text+0x23): undefined reference to `func7'
main.c:(.text+0x28): undefined reference to `func8'
main.c:(.text+0x2d): undefined reference to `func9'
main.c:(.text+0x32): undefined reference to `func10'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Update** Nevermind, I forgot to re-generate the project files with `gen_srcs.py` after moving `$!Libs` after `$!<`.

**Comment by winksaville** [comment]
I was unaware of the -e option, I need to RTFM thoroughly :)

Yes the backend performance is what's important, I was surprised how fast
CMakes make file backed is. Not as fast as Ninja but still pretty fast.
Anyway, I'm looking forward to seeing how Creator scales.

**Comment by winksaville** [comment]
I'm using Ninja 1.6

**Comment by winksaville** [comment]
I've found a solution to the build problem there is no dependency on libL000.a by main.o in the generated build.ninja file.

Changing:

```
build /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o: testapp_obj_0000 /home/wink/prgs/test/gen_srcs/test/apps/testapp/src/main.c
```

To below which adds libL000.a as a dependency:

```
build /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o: testapp_obj_0000 /home/wink/prgs/test/gen_srcs/test/build/libs/libL000.a /home/wink/prgs/test/gen_srcs/test/apps/testapp/src/main.c
```

Works for me and I now see step [2/4] creating the library before compiling main.o int step [3/4]. But I don't no how to change the template.app.creator or ... to express the dependency.

```
$ ninja -v
[1/4] gcc -c -std=c99 -I/home/wink/prgs/test/gen_srcs/test/libs/L000/include -o /home/wink/prgs/test/gen_srcs/test/build/obj/L000/L000.o /home/wink/prgs/test/gen_srcs/test/libs/L000/src/L000.c
[2/4] ar rcs /home/wink/prgs/test/gen_srcs/test/build/libs/libL000.a /home/wink/prgs/test/gen_srcs/test/build/obj/L000/L000.o
[3/4] gcc -c -I/home/wink/prgs/test/gen_srcs/test/apps/testapp/include -I/home/wink/prgs/test/gen_srcs/test/libs/L000/include -std=c99 /home/wink/prgs/test/gen_srcs/test/apps/testapp/src/main.c -o /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o
[4/4] gcc -std=c99 /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o /home/wink/prgs/test/gen_srcs/test/build/libs/libL000.a -o /home/wink/prgs/test/gen_srcs/test/build/bin/testapp
```

Here is the non working sequence and we see that step [2/4] is compiling main.o and step [3/4] is linking and step [4/4] was going to be creating libL000.a:

```
$ cd ..
$ rm -rf test
$ ./gen_srcs.py creator test 1 1
$ cd test
$ creator -e

==> creator: exporting to: build.ninja
$ ninja -v
[1/4] gcc -c -std=c99 -I/home/wink/prgs/test/gen_srcs/test/libs/L000/include -o /home/wink/prgs/test/gen_srcs/test/build/obj/L000/L000.o /home/wink/prgs/test/gen_srcs/test/libs/L000/src/L000.c
[2/4] gcc -c -I/home/wink/prgs/test/gen_srcs/test/apps/testapp/include -I/home/wink/prgs/test/gen_srcs/test/libs/L000/include -std=c99 /home/wink/prgs/test/gen_srcs/test/apps/testapp/src/main.c -o /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o
[3/4] gcc -std=c99 /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o /home/wink/prgs/test/gen_srcs/test/build/libs/libL000.a -o /home/wink/prgs/test/gen_srcs/test/build/bin/testapp
FAILED: gcc -std=c99 /home/wink/prgs/test/gen_srcs/test/build/obj/testapp/main.o /home/wink/prgs/test/gen_srcs/test/build/libs/libL000.a -o /home/wink/prgs/test/gen_srcs/test/build/bin/testapp
gcc: error: /home/wink/prgs/test/gen_srcs/test/build/libs/libL000.a: No such file or directory
ninja: build stopped: subcommand failed.
```

**Comment by NiklasRosenstein** [comment]
Of course! Good catch! I didn't list the libraries as inputs to the `bin` target of the application. I'll fix that tomorrow. I might need to think about a good way to extend requirements of an inherited target.

**Comment by winksaville** [comment]
SG, and when you've got more time it would be great if would get some more
documentation so mere mortals could use Creator, not just God :)

**Comment by NiklasRosenstein** [comment]
Hey Wink, I just wrote a little tutorial, and I hope it contains enough information to start with. But let me know if you have any critics. https://github.com/creator-build/creator/wiki/Creator-Tutorial

**Comment by winksaville** [comment]
I'd sure like to directly comment on the tutorial page, maybe you should
copy it into a Google Doc or maybe as a ".md" file in a creator/doc
directory? Here are a few comments:
- Its a great start and I now get a better feel for Creator
- I suggest starting with the simplest Helloworld Creator possible and
  explain every line and every field. Than start adding features like macros.
  A critical thing is to explain what '@target' is. From my neophyte point of
  view having @target for 'def program' be @target('objects') is funny. If
  program needs to refer to the function objects why not just pass it in as a
  named parameter and just use the annotation @target with no parameter
  always? (I'm sure that's a stupid question, but I'm trying to explain why I
  think the current syntax seems funny). Anyway, below I've tried to simplify
  the Creator from hello_world.cpp example so it has no macros.

# @creator.unit.name = creator.hello.cpp

load('platform', 'p')
load('compiler', 'c')

# Create objects

@target()
def objects():
  objects.build_each(
    '$ProjectPath/src/hello.cpp',
    '($p:obj $ProjectPath/build/obj/hello.o'),
    '$c:cpp $(c:objout $@) $'<)

# Create executable program

@target(objects) # Why isn't this 'program'?
def program():
  program.build(
    '($p:obj $ProjectPath/build/obj/hello.o'),
    '($p:bin $ProjectPath/build/bin/hello'),
    '$c:cpp $(c:binout $@) $'<)

Actually I'd would hope it could be simpler, maybe something like the code
below. I assume you could infer the proper command line from the OUTPUT and
INPUT parameters to program.build:

# @creator.unit.name = creator.hello.cpp

load('platform', 'p')
load('compiler', 'c')

# Create executable program

@target()
def program():
  program.build(
    '$ProjectPath/src/hello.cpp',
    '($p:bin $ProjectPath/bin/hello'),
    '$c:cpp')

A question about your define macros, would it be possible to just use
Python assignment statements and named parameters something like below. It
seems simpler and less visually noisy. Not a big deal, just check'n.

 # Get a list of 'list' of files some how
Sources = glob('$ProjectPath/src/*.cpp')

# Define the destination object directory

Objects = '$ProjectPath/build/obj'

@target()
def objects():
  objects.build_each(
    input_list=Sources,
    output_dir=Objects,
    builder='$c:cpp ...')

My first thoughts,

-- Wink

**Comment by winksaville** [comment]
Niklas,

You haven't responded to my email, I hope I didn't offend you with my
suggestions. They are just my opinion and no offense would be taken if you
feel I'm way off base, just let me know.

-- Wink

**Comment by NiklasRosenstein** [comment]
Hey Wink! That's not the case, I was just busy doing other things. :) I value your feedback.
- I'll add a link to the tutorial in the README so people can find it more easily
- Your example of a simplest possible example makes sense and I'm sure it'll help people understand better, thanks
- I could make it `@target(requires=objects)` or `@target(requires=[objects, some_library])`, the named argument would make it more obvious. Alternatively, you can use `program.requires(objects)` from the function body or after the function was declared on the global level

---

``` python
@target()
def program():
  program.build(
    '$ProjectPath/src/hello.cpp',
    '($p:bin $ProjectPath/bin/hello'),
    '$c:cpp')
```

You could make the `$c:cpp` macro reference `$<` and `$@` and it would work, but if you don't want an executable but an object file, you need a different command than `$c:cpp`. Sure, on Linux you could just add the `-c` option but on Windows with MSVC, there is a different output parameter for the object and executable filename (`/Fe` and `/Fo`). That is why there is `$(c:binout ...)` and `$(c:objout ...)`. They don't differ for GCC and Clang, but for the MSVC compiler. The goal is to find a common interface for most or all compilers wherever possible.

---

The problem with using just Python variables is that I can't intercept the variable assignment. If you do

``` python
Defines = 'SOME_DEFINE'
if Debug:
   Defines = '$Defines;SOME_DEFINE'
```

I need to resolve the `$Defines` reference and replace it by its original value, otherwise it generates a cyclic reference of the variable and an infinite recursion on evaluation. Also using a format such as

``` python
Sources = glob('$ProjectPath/src/*.cpp')
```

would be rather inconsistent when macro functions would still be used. Maybe one could make it something like the following, but if you still have in-text macro functions, it gets very inconsistent. Also, you wouldn't get "lazy evaluation".

``` python
Objects = p.obj(move(Sources, '$ProjectPath/src', '$ProjectPath/build'))
Executable = p.bin('$ProjectPath/build/main-$(upper $arch)')
```

Also, I don't know whether I should parse the value of `Sources` into a new macro (as if you had used a literal string) or not, since the Python function receives a string in both cases. As you might see, it involves a lot of problems.

I agree that the above would be easier on the eye though.

**Comment by winksaville** [comment]
See inline below:

On Tue, Aug 18, 2015 at 10:03 AM Niklas Rosenstein notifications@github.com
wrote:

> Hey Wink! That's not the case, I was just busy doing other things. :) I
> value your feedback.
> - I'll add a link to the tutorial in the README so people can find it
>   more easily
> 
> prefect.
> - Your example of a simplest possible example makes sense and I'm sure
>   it'll help people understand better, thanks
> 
> See the Meson's tutorial
> https://github.com/mesonbuild/meson/wiki/Tutorial as an example.
> - I could make it @target(requires=objects) or @target(requires=[objects,
>   some_library]), the named argument would make it more obvious.
>   Alternatively, you can use program.requires(objects) from the function
>   body or after the function was declared on the global level
> 
> So you can use programs.requires(objects) or @target(objects) now?
> Personally I like the '.requires' style better as its more obvious to me.
> Using named parameters is better, but I like being explicit.

Related question, you used "requires" to solve the library dependency bug I
found, could you have used @target for that instead? I ask because it think
three should be only one way to define the dependency graph, either always
use @target or xxx.requires.

> ---
> 
> @target()def program():
>   program.build(
>     '$ProjectPath/src/hello.cpp',
>     '($p:bin $ProjectPath/bin/hello'),
>     '$c:cpp')
> 
> You could make the $c:cpp macro reference $< and $@ and it would work,
> but if you don't want an executable but an object file, you need a
> different command than $c:cpp. Sure, on Linux you could just add the -c
> option but on Windows with MSVC, there is a different output parameter for
> the object and executable filename (/Fe and /Fo). That is why there is $(c:binout
> ...) and $(c:objout ...). They don't differ for GCC and Clang, but for
> the MSVC compiler. The goal is to find a common interface for most or all
> compilers wherever possible.
> 
> So maybe it should be program.build_executable and program.build_object, I
> guess it seems funny to me that you have "inputs" and "outputs" and then
> have to use restate those using the $@ and $< syntax with the
> $(c:cpp|binout|objout ...) parameters. I definitely like I can provide my
> own compiler line if necessary, but always having to supply it seems too
> verbose. BTW, I think using named parameters would be better rather than
> positional, but that's just me :)

---

> The problem with using just Python variables is that I can't intercept the
> variable assignment. If you do
> 
> Defines = 'SOME_DEFINE'if Debug:
>    Defines = '$Defines;SOME_DEFINE'
> 
> I need to resolve the $Defines reference and replace it by its original
> value, otherwise it generates a cyclic reference of the variable and an
> infinite recursion on evaluation. Also using a format such as
> 
> Sources = glob('$ProjectPath/src/*.cpp')
> 
> would be rather inconsistent when macro functions would still be used, or
> you'd have to write many ' like
> 
> Objects = p.obj(move(Sources, '$ProjectPath/src', '$ProjectPath/build'))
> 
> Also, I don't know whether I should parse the value of Sources into a new
> macro (as if you had used a literal string) or not, since the Python
> function receives a string in both cases. As you might see, it involves a
> lot of problems.
> 
> Being more Python maybe a bad idea, but what about using 'format' something
> like:

Defines = 'SOME_DEFINES'
if Debug:
    Defines = '{0};ANOTHER_DEFINE'.format(Defines)

On one hand your code is "pure" Python, but in reality you've created a DSL
to extend Python and thus I'm not sure when I can use Python and when I
have to use your DSL. Again, I've almost no Python experience so take
anything I say with a huge grain of salt, but I do think I represent a
somewhat typical user.

**Pull request merged**
