### PR TITLE
Updated to new target declaration syntax of Creator 0.0.4-dev

### PR DESCRIPTION
**Pull request by NiklasRosenstein**

### CODE REVIEW

**Comment by winksaville** [comment]
NICE!

AFAICT of the 4 commits change 622f804 is the only new one that needs to be merged. Could you rebase the pull request so that only new changes are in the pull request?

**Comment by NiklasRosenstein** [comment]
Hey Wink. Sorry, I don't know how to do that. I can rebase the changes instead of merging them, but it would still be the four commits.

**Comment by winksaville** [comment]
Ok, I'll look into some more and get back to you.

**Comment by winksaville** [comment]
I think there are several solutions, basically I think you should do your
work on a "topic" branch not on master. So I'd create a new branch
cherry-pick your change to that branch. Then sync your master back with my
master branch and make it exactly the same as my master branch. Then create
another branch off master and cherry-pick your change to this new branch.
Hopefully that makes sense, if not I can just checkout your branch and
cherry-pick it to my branch, but then you'll attribution. As with most
things git there a multitude of ways to do anything, so ...

Of course, we might also just put this off until you create Craftr.

**Pull request closed without merging**
